# Generated by Django 3.1.7 on 2021-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20210419_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='img',
            field=models.ImageField(null=True, upload_to='static/pics'),
        ),
    ]
