# Generated by Django 3.1.7 on 2021-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20210419_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='img',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
